version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.16.0
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@16.0.0
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration=production
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/aws-app/ s3://your-aws-s3-bucket-name --delete